In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
df = pd.read_csv('C:/Users/sakin_xyc6lmd/OneDrive/Desktop/Infotact internship projects/Multi-Touch_Attribution_Project/multi-touch-attribution/multi_touch_attribution_data.csv')

In [3]:
df.head(20)

,User ID,Timestamp,Channel,Campaign,Conversion
0,83281,2025-02-10 07:58:51,Email,New Product Launch,No
1,68071,2025-02-10 23:38:48,Search Ads,Winter Sale,No
2,90131,2025-02-11 10:41:07,Social Media,Brand Awareness,Yes
3,71026,2025-02-10 08:19:44,Direct Traffic,-,Yes
4,94486,2025-02-10 15:15:46,Email,Retargeting,Yes
5,31134,2025-02-11 06:43:06,Search Ads,-,Yes
6,99995,2025-02-10 06:15:30,Search Ads,-,Yes
7,45832,2025-02-11 01:09:27,Referral,Winter Sale,Yes
8,79863,2025-02-10 06:48:56,Display Ads,Discount Offer,Yes
9,35324,2025-02-10 21:36:24,Direct Traffic,-,No
10,50905,2025-02-11 22:04:52,Social Media,Brand Awareness,No
11,82798,2025-02-10 08:57:09,Display Ads,New Product Launch,Yes
12,53313,2025-02-10 14:45:33,Social Media,Brand Awareness,Yes
13,59109,2025-02-10 14:18:50,Display Ads,Brand Awareness,No
14,72045,2025-02-11 18:39:11,Referral,Retargeting,No
15,91019,2025-02-10 04:28:34,Email,Winter Sale,No
16,78241,2025-02-11 11:24:51,Display Ads,Brand Awareness,Yes
17,71565,2025-02-11 17:24:00,Email,Retargeting,Yes
18,60684,2025-02-10 01:31:38,Email,-,Yes
19,28998,2025-02-11 11:15:57,Direct Traffic,-,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  object
 2   Channel     10000 non-null  object
 3   Campaign    10000 non-null  object
 4   Conversion  10000 non-null  object
dtypes: int64(1), object(4)
memory usage: 390.8+ KB

In [5]:
df.describe(include='all')

            User ID            Timestamp         Channel Campaign Conversion
count   10000.00000                10000           10000    10000      10000
unique          NaN                 9737               6        6          2
top             NaN  2025-02-10 18:23:09  Direct Traffic        -         No
freq            NaN                    3            1721     3131       5056
mean    54957.01700                  NaN             NaN      NaN        NaN
std     25685.14741                  NaN             NaN      NaN        NaN
min     10028.00000                  NaN             NaN      NaN        NaN
25%     32391.00000                  NaN             NaN      NaN        NaN
50%     55446.00000                  NaN             NaN      NaN        NaN
75%     77298.00000                  NaN             NaN      NaN        NaN
max     99995.00000                  NaN             NaN      NaN        NaN

In [6]:
df.shape

(10000, 5)

In [7]:
df.isnull().sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [8]:
df['Channel'].unique()

array(['Email', 'Search Ads', 'Social Media', 'Direct Traffic',
       'Referral', 'Display Ads'], dtype=object)

In [9]:
df['Campaign'].unique()

array(['New Product Launch', 'Winter Sale', 'Brand Awareness', '-',
       'Retargeting', 'Discount Offer'], dtype=object)

In [10]:
df['Conversion'].unique()

array(['No', 'Yes'], dtype=object)

In [11]:
df['Timestamp'].min(), df['Timestamp'].max()

('2025-02-10 00:00:22', '2025-02-11 23:59:58')

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.shape
df['User ID'].nunique()

2847

In [14]:
df.groupby('User ID').size().describe()

count    2847.000000
mean        3.512469
std         1.770702
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        12.000000
dtype: float64

In [15]:
df['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [16]:
(df['Campaign'] == '-').sum()

np.int64(3131)

In [17]:
df['Timestamp'].dtype

dtype('O')

In [18]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [19]:
df['Timestamp'].dtype

dtype('<M8[ns]')

In [20]:
df['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [21]:
df['Campaign'].value_counts()

Campaign
-                     3131
New Product Launch    1416
Retargeting           1379
Brand Awareness       1378
Winter Sale           1372
Discount Offer        1324
Name: count, dtype: int64

In [22]:
df['Channel'].unique()

array(['Email', 'Search Ads', 'Social Media', 'Direct Traffic',
       'Referral', 'Display Ads'], dtype=object)

In [23]:
df['Campaign'] = df['Campaign'].replace('-', 'No Campaign')

In [24]:
df['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [25]:
df['Campaign'].value_counts()

Campaign
No Campaign           3131
New Product Launch    1416
Retargeting           1379
Brand Awareness       1378
Winter Sale           1372
Discount Offer        1324
Name: count, dtype: int64

In [26]:
df['Conversion'] = df['Conversion'].map({'Yes': 1, 'No': 0})

In [28]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [29]:
import pandas as pd
from sqlalchemy import create_engine

df['Conversion'] = df['Conversion'].map({'Yes': 1, 'No': 0})

df.to_csv('multi_touch_attribution_cleaned.csv', index=False)

engine = create_engine("mysql+pymysql://root:2001@127.0.0.1:3306/multi_touch_attribution")

df_sql = df.rename(columns={
    'User ID': 'user_id',
    'Timestamp': 'timestamp',
    'Channel': 'channel',
    'Campaign': 'campaign',
    'Conversion': 'conversion'
})

df_sql.to_sql("interactions", con=engine, if_exists="append", index=False)
print("Loaded", len(df_sql), "rows into interactions")

Loaded 10000 rows into interactions

In [30]:
# 1. Reload raw data fresh
df = pd.read_csv('C:/Users/sakin_xyc6lmd/OneDrive/Desktop/Infotact internship projects/Multi-Touch_Attribution_Project/multi-touch-attribution/multi_touch_attribution_data.csv')

# 2. Clean it
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['Campaign'] = df['Campaign'].replace('-', 'No Campaign')
df['Conversion'] = df['Conversion'].map({'Yes': 1, 'No': 0})

# 3. Rename and load
df_sql = df.rename(columns={
    'User ID': 'user_id',
    'Timestamp': 'timestamp',
    'Channel': 'channel',
    'Campaign': 'campaign',
    'Conversion': 'conversion'
})

df_sql.to_sql("interactions", con=engine, if_exists="replace", index=False)
print("Loaded", len(df_sql), "rows into interactions")

Loaded 10000 rows into interactions